# Generated by Django 4.0.3 on 2022-06-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_department_professor_answer_selection_question_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookmark',
            field=models.ManyToManyField(to='qna.question'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ManyToManyField(to='qna.department'),
        ),
    ]
